# Generated by Django 4.0.2 on 2022-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body_post_created_at_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(db_index=True, default=0, verbose_name='like_count'),
        ),
    ]
